trainingdata <- read.table("X_train.txt")
testdata <- read.table ("X_test.txt")
traininglabels <- read.table("y_train.txt")
trainsubjectids <- read.table("subject_train.txt")
testsubjectids <- read.table("subject_test.txt")
subjectids <- rbind(trainsubjectids, testsubjectids)
traininglabels$V1 <- as.character(traininglabels$V1)
traininglabels$V1 <- gsub("1", "Walking", traininglabels$V1, fixed=TRUE)
traininglabels$V1 <- gsub("2", "Walking up stairs", traininglabels$V1, fixed=TRUE)
traininglabels$V1 <- gsub("3", "Walking down stairs", traininglabels$V1, fixed=TRUE)
traininglabels$V1 <- gsub("4", "Sitting", traininglabels$V1, fixed=TRUE)
traininglabels$V1 <- gsub("5", "Standing", traininglabels$V1, fixed=TRUE)
traininglabels$V1 <- gsub("6", "Laying", traininglabels$V1, fixed=TRUE)
testlabels <- read.table("y_test.txt")
testlabels$V1 <- as.character(testlabels$V1)
testlabels$V1 <- gsub("1", "Walking", testlabels$V1, fixed=TRUE)
testlabels$V1 <- gsub("2", "Walking up stairs", testlabels$V1, fixed=TRUE)
testlabels$V1 <- gsub("3", "Walking down stairs", testlabels$V1, fixed=TRUE)
testlabels$V1 <- gsub("4", "Sitting", testlabels$V1, fixed=TRUE)
testlabels$V1 <- gsub("5", "Standing", testlabels$V1, fixed=TRUE)
testlabels$V1 <- gsub("6", "Laying", testlabels$V1, fixed=TRUE)
mergeddata <- rbind(trainingdata, testdata)
mergedlabels <- rbind(traininglabels, testlabels)
mergeddataandlabels <- cbind(mergedlabels, mergeddata)
mergeddataandlabels <- cbind(subjectids, mergeddataandlabels)
featurenames <- read.table("features.txt")
names <- c("subjects", "activities", as.character(featurenames[,2]))
names (mergeddataandlabels) <- c(names)
i <- grep(".mean.", names(mergeddataandlabels))
i <- c(1,2,i)
j <- grep(".std.", names(mergeddataandlabels))
extractmeans <- mergeddataandlabels[, i]
extractstds <- mergeddataandlabels [,j]
extract <- cbind(extractmeans,extractstds)
newnames <- tolower(names(extract))
newnames <- gsub("-","",newnames)
newnames <- gsub("\\(|\\)","",newnames)
names (extract) <- c(newnames)
extract [1,1] = 1
extract[7353,1] = 2
extract [1,2] = "Standing"
extract [7353,2] = "Standing"
library(dplyr)
extractGroups <- group_by(extract, subjects, activities)
result <- summarise_each (extractGroups,(funs(mean)))
write.table(result, file = "result.txt", row.name=FALSE)

